### ISSUE TITLE
`PXE004.001 DTS option is available and works correctly` fails on laptops

### ISSUE THREAD

**Issue by mkopec** [Dasharo/open-source-firmware-validation#170] opened 2023-12-21 17:12 UTC
### Device

NovaCustom *

### RTE version

n/a - PiKVM

### Affected component(s) or functionality

Automated testing of netboot functionality

### Brief summary

The test fails, because it expects to find DTS on serial console, but on laptops we only get EFI serial console via EC

### How reproducible

100%

### How to reproduce

- Run network boot test suite

### Expected behavior

Tests correctly detect that DTS netboot works correctly

### Actual behavior

Tests fail because they don't consider that on laptops we don't get OS serial output

### Link to screenshots or logs

most relevant excerpt:
![image](https://github.com/Dasharo/open-source-firmware-validation/assets/3678707/b9770519-168f-4a34-b285-a392a278b24a)

full log:
[logs.tar.gz](https://github.com/Dasharo/open-source-firmware-validation/files/13744509/logs.tar.gz)

**Comment by philipandag** [comment] 2024-08-27 08:00
This test is marked as manual since V54x_MTL V54x_MTL v0.9.0-rc2 so it is not a bug. Automating the test could be a feature to add in the future.

**Closed by philipandag** 2024-08-27 08:00 UTC
Labels: bug, test-stand, laptops
