### ISSUE TITLE
MNE - Me-Neuter tests fail on MSI

### ISSUE THREAD

**Issue by JanPrusinowski** [Dasharo/open-source-firmware-validation#536] opened 2024-10-16 08:57 UTC
### Device

msi-pro-z690-a-wifi-ddr4

### RTE version

1.1.4

### OSFV version

develop

### Affected component(s) or functionality

me-neuter tests

### Brief summary

Set UEFI Option is unable to set Intel ME mode

### How reproducible

100%

### How to reproduce

`robot -v snipeit:no -L TRACE -v rte_ip:192.168.10.199 -v config:msi-pro-z690-a-wifi-ddr4 -v sonoff_ip:192.168.10.169 -v pikvm_ip:192.168.10.16 -v device_ip:192.168.10.155 -v fw_file:./msi_ms7d25_v1.1.4_ddr4.rom dasharo-security/me-neuter.robot`

### Expected behavior

Intel ME mode is set to correct value

### Actual behavior

Test fails on trying to set the option.

### Link to screenshots or logs

![image](https://github.com/user-attachments/assets/bf4e11e2-4bb5-4d1c-9f20-743a428a37bb)
![image](https://github.com/user-attachments/assets/f3c43a60-9565-48e2-b8eb-90f5768ba793)
[log2.zip](https://github.com/user-attachments/files/17392485/log2.zip)

**Comment by macpijan** [comment] 2024-10-16 11:45
It appears that help text is being parsed, instead of the menu text.

I'd start with confirming whether it is reproducible, or if it was some one-time problem.

**Comment by macpijan** [comment] 2024-10-17 18:08
The reason of this failure is addition of these two help text lines in the selectable options area:

![image](https://github.com/user-attachments/assets/05f3ddcc-3005-439a-b786-4f3319bf3830)

@BeataZdunczyk Can we try to ensure that we run some test working on certain menu when adding changes to such menus?

**Comment by macpijan** [comment] 2024-10-23 12:04
@BeataZdunczyk @JanPrusinowski So the solution would be to ignore the lines marked in yellow when parsing.

We've had something like this that checked if line was on option we could select, and dropped otherwise: https://github.com/Dasharo/open-source-firmware-validation/blob/develop/lib/bios/menus.py#L7

My suggestion would be:
- analyze the call trace - is this keyword used here?
- if no - why not, can we use it here?
- if yes - why it does not work? can we come up with better regexp?

**Comment by JanPrusinowski** [comment] 2024-10-23 12:26
The best solution would be avoiding adding any arguments to `Set UEFI Option`. Would be nice to see a solution which is automatic. In this case there is a problem because this yellow section contains the string with the option name. Maybe checking if the option exists more than once in the list would be a good approach.

**Comment by macpijan** [comment] 2024-10-23 17:20
> In this case there is a problem because this yellow section contains the string with the option name. Maybe checking if the option exists more than once in the list would be a good approach.

The linked keyword does not rely on option name to determine whether entry in menu can be selected or not.

The general rule is that if a line either:
- starts with `>`
- or has some `[]`  or `<>` later on
then this line is something we want to include in parsed menu.

**Comment by miczyg1** [comment] 2024-12-16 17:12
PR #580 merged, closing

**Closed by miczyg1** 2024-12-16 17:12 UTC
Labels: bug
